### PR TITLE
Update urlview.c

### PR DESCRIPTION
**Pull request by mexas**
unsigned char here seems to be wrong.
It doesn't build with clang or
with GCC -Werror. Using just char
make it build and run fine on FreeBSD
amd64 and ia64 10.0

### CODE REVIEW

**Comment by sigpipe** [comment]
Can you please specify which compiler options you were using, and the exact error?  I just tried with gcc -std=gnu99 -Wall -W -pedantic and there is no error related to that function.

**Comment by mexas** [comment]
The default system compiler on FreeBSD 10 is still 4.2.1:

# cc --version

cc (GCC) 4.2.1 20070831 patched [FreeBSD]
Copyright (C) 2007 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

# 

With your options I get:

cc -DPACKAGE=\"urlview\" -DVERSION=\"0.9\" -DHAVE_CURS_SET=1 -DHAVE_NCURSES_H=1 -DHAVE_SNPRINTF=1 -DHAVE_REGEX_H=1 -DHAVE_STDARG_H=1  -I. -I.     -O2 -pipe -I/usr/local/include -std=gnu99 -Wall -W -pedantic -fno-strict-aliasing -DURLVIEW -Dunix -c urlview.c
--- enter.o ---
cc -DPACKAGE=\"urlview\" -DVERSION=\"0.9\" -DHAVE_CURS_SET=1 -DHAVE_NCURSES_H=1 -DHAVE_SNPRINTF=1 -DHAVE_REGEX_H=1 -DHAVE_STDARG_H=1  -I. -I.     -O2 -pipe -I/usr/local/include -std=gnu99 -Wall -W -pedantic -fno-strict-aliasing -DURLVIEW -Dunix -c enter.c
--- urlview.o ---
urlview.c: In function 'search_backward':
urlview.c:107: warning: unused parameter 'urlcount'
urlview.c: In function 'main':
urlview.c:506: warning: pointer targets in passing argument 1 of 'mutt_enter_string' differ in signedness
urlview.c:534: warning: pointer targets in passing argument 1 of 'mutt_enter_string' differ in signedness
urlview.c:562: warning: pointer targets in passing argument 1 of 'mutt_enter_string' differ in signedness
urlview.c:567: warning: pointer targets in passing argument 1 of 'mutt_enter_string' differ in signedness
--- enter.o ---
enter.c: In function 'mutt_enter_string':
enter.c:469: warning: comparison between signed and unsigned
enter.c:144: warning: unused variable 'tempbuf'
--- urlview.o ---
urlview.c:147: warning: unused parameter 'argc'

I haven't got an amd64 box right now, but I think clang gives errors instead.
I'll get back to you on this.

**Comment by sigpipe** [comment]
I just tested:  CC=clang CFLAGS='-Wall -pedantic' ./configure

With clang 3.2.1 and there were no warnings or errors reported.

**Comment by sigpipe** [comment]
Ok, I missed that it was amd64, that could make a difference.

**Comment by sigpipe** [comment]
I just noticed that your line numbers don't match up with what is in the repo?  Are you compiling out of the git repo, or did you pick up the urlview .tar.gz ?  Please test against the git repo.

**Comment by mexas** [comment]
you are right. I must be confusing myself.
I made a tar.gz from the repo, r15, and it
builds fine.

**Pull request closed without merging**
